services:
  nginx:
      image: nginx
      ports:
        - 80:80
        - 443:443
      restart: always
      volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/:ro
        # needs both /live & /archive
        - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro 
        - ./certbot/var/www/acme/:/var/www/acme/:ro
        - ./packages/frontend/dist/:/usr/share/nginx/html/:ro
