services:

  app:
      build: .
      container_name: apple_tryout_node_app
      ports:
        - 6060:6060
      command: yarn workspace backend start
      environment:
        - NODE_ENV=production
      volumes:
        - ./packages/frontend/dist/:/app/packages/frontend/dist/
  
  nginx:
      image: nginx
      ports:
        - 80:80
        - 443:443
      restart: always
      volumes:
        - ./nginx/conf/:/etc/nginx/conf.d/:ro
        # needs both /live & /archive
        - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro 
        - ./certbot/var/www/acme/:/var/www/acme/:ro
        - ./packages/frontend/dist/:/usr/share/nginx/html/:ro
